# Generated by Django 6.0.5 on 2026-06-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_servicecategory_companyprofile_slug_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
