# Generated by Django 6.0.5 on 2026-06-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_companyprofile_slug'),
    ]

    operations = [
    ]
