# Generated by Django 6.0.5 on 2026-06-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_companyprofile_cover_photo_companyprofile_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='allowed_for_partner_types',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='monthly_revenue',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='total_guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='total_reservations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='yearly_revenue',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
