# Generated by Django 6.0.5 on 2026-06-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('sve', 'Sve'), ('infrastruktura', 'Infrastruktura'), ('vremenska prognoza', 'Vremenska prognoza'), ('sport', 'Sport'), ('aktivnosti', 'Aktivnosti'), ('dogadjaji', 'Dogadjaji')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='vesti/')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
