# Generated by Django 6.0.5 on 2026-06-15 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='vest',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vesti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vest',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vest',
            name='priority',
            field=models.CharField(choices=[('nizak', 'Nizak'), ('srednji', 'Srednji'), ('visok', 'Visok')], default='srednji', max_length=10),
        ),
        migrations.AddField(
            model_name='vest',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vest',
            name='seo_desc',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='vest',
            name='seo_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='vest',
            name='status',
            field=models.CharField(choices=[('nacrt', 'Nacrt'), ('objavljeno', 'Objavljeno'), ('zakazano', 'Zakazano')], default='nacrt', max_length=20),
        ),
        migrations.AddField(
            model_name='vest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vest',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vest',
            name='tags',
            field=models.ManyToManyField(blank=True, to='vesti.tag'),
        ),
    ]
