# Generated by Django 6.0.5 on 2026-06-15 14:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0002_tag_vest_author_vest_is_visible_vest_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vest',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
