# Generated by Django 6.0.5 on 2026-06-17 14:27

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_companyprofile_cover_photo_companyprofile_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dogadjaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('opis', models.TextField(blank=True)),
                ('kategorija', models.CharField(choices=[('koncerti', 'Koncerti'), ('takmicenja', 'Takmicenja'), ('festivali', 'Festivali'), ('edukacija', 'Edukacija')], max_length=20)),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('all_year', 'All Year')], default='all_year', max_length=10)),
                ('datum_pocetka', models.DateField()),
                ('datum_zavrsetka', models.DateField(blank=True, null=True)),
                ('vreme', models.TimeField(blank=True, null=True)),
                ('lokacija', models.CharField(blank=True, max_length=255)),
                ('cena', models.DecimalField(blank=True, decimal_places=2, help_text='Ostavite prazno za besplatne dogadjaje', max_digits=10, null=True)),
                ('max_kapacitet', models.IntegerField(blank=True, help_text='Ostavite prazno za neogranicen broj', null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogadjaji', to='users.companyprofile')),
            ],
            options={
                'verbose_name': 'Dogadjaj',
                'verbose_name_plural': 'Dogadjaji',
                'ordering': ['datum_pocetka'],
            },
        ),
        migrations.CreateModel(
            name='DogadjajReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_karata', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('napomena', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dogadjaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervacije', to='dogadjaji.dogadjaj')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogadjaj_rezervacije', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
