# Generated by Django 6.0.5 on 2026-06-17 14:27

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_companyprofile_cover_photo_companyprofile_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Smestaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('opis', models.TextField(blank=True)),
                ('tip', models.CharField(choices=[('hotel', 'Hotel'), ('apartman', 'Apartman'), ('vila', 'Vila & Brvnara')], default='hotel', max_length=20)),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('all_year', 'All Year')], default='all_year', max_length=10)),
                ('cena_po_nocenju', models.DecimalField(decimal_places=2, max_digits=10)),
                ('udaljenost_od_staza', models.IntegerField(default=0, help_text='Udaljenost u metrima')),
                ('kapacitet', models.IntegerField(default=1)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('ima_spa', models.BooleanField(default=False)),
                ('ima_bazen', models.BooleanField(default=False)),
                ('ski_in_ski_out', models.BooleanField(default=False)),
                ('ima_restoran', models.BooleanField(default=False)),
                ('ima_parking', models.BooleanField(default=False)),
                ('ima_wifi', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smestaji', to='users.companyprofile')),
            ],
            options={
                'verbose_name': 'Smestaj',
                'verbose_name_plural': 'Smestaji',
                'ordering': ['cena_po_nocenju'],
            },
        ),
        migrations.CreateModel(
            name='SmestajReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('broj_odraslih', models.IntegerField(default=1)),
                ('broj_dece', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('napomena', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('smestaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervacije', to='smestaj.smestaj')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smestaj_rezervacije', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
