# Generated by Django 6.0.5 on 2026-06-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smestaj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smestajreservation',
            name='revenue_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smestajreservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
