# Generated by Django 6.0.5 on 2026-06-17 07:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkiPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('pass_type', models.CharField(choices=[('daily', 'Daily'), ('daily3', 'Daily3'), ('weekly', 'Weekly'), ('seasonal', 'Seasonal')], max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ski_passes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
